### PR TITLE
Added 'You might not need jQuery'

### PR DESCRIPTION
**Pull request by arthurvr**
Added youmightnotneedjquery.com

### CODE REVIEW

**Comment by arthurvr** [comment]
@dypsilon Ping? There are 42 open pull requests in this repo...

**Comment by dypsilon** [comment]
Yes, thank you. I will take time soon to batch process them, much easier as doing them one by one because of the conflicts. I'm also working on a better way to manage and browse this list.

**Comment by arthurvr** [comment]
@dypsilon Perfectly fine bro. Maybe you should consider adding another collaborator to this repo? Don't take me wrong, just a suggestion and I'm not suggesting anyone in specific, but having many open issues/PRs doesn't encourage new contributions.

**Comment by dypsilon** [comment]
@arthurvr thanks for your advice, I'm not trying to encourage new contributions right now, because this list is pretty unmanagable as is. Just hope it's useful in it's current form until I have a better solution.

**Comment by aemonge** [comment]
@arthurvr  Thanks a LOT men!!! It really cleared my mind. I knew thing would end up this way, but never though they already did. =^.^=

**Pull request closed without merging**
