### PR TITLE
Update link to Folktale as the old domain is outdated

### PR DESCRIPTION
**Pull request by kyusu**
Hi @dypsilon,

I've updated the links to the Folktale documentation. The old domain [folktalejs.org](http://folktalejs.org) has unfortunately been given up by the Folktale author and now redirects you to some commercial pages. The new domain is [folktale.origamitower.com](http://folktale.origamitower.com).

Regards
Kyusu

### CODE REVIEW

**Comment by dypsilon** [comment]
Thank you!

**Review by EMIL23GRA — COMMENTED** [review]
@emil

**Comment by ghost** [comment]
[50ed051c96428af9d4f020305ca206587514e121](https://tools.ietf.org/html/rfc67490))

**Comment by ghost** [comment]
https://tools.ietf.org/html/rfc67490)

**Pull request merged**
